 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: cd practiceperfect
       - run: yarn
       - run: yarn lint
       # TEST
       # DEPLOY
